### ISSUE TITLE
这是一个什么样的项目？

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/datatree#1]
云大，一直关注您，开新坑，来个Readme嘛。

**Comment by Gowa2017** [comment]
看了您的博客。

这个岂不是和 stm 非常的相似的方式。
不过是进行了惰性展开

**Comment by cloudwu** [comment]
这次主要是重新设计了序列化结构，为每张表关联了唯一 id ，方便更新。

**Comment by Gowa2017** [comment]
STM 是要么全更新，要么全展开。

当前这个的话提供了 LUA 层面的 API来获取序列化后指定位置的数据 。
